mercure:
    hubs:
        default:
            url: '%env(MERCURE_dock_URL)%'
            public_url: '%env(MERCURE_dock_PUBLIC_URL)%'
            jwt:
                secret: '%env(MERCURE_JWT_SECRET)%'
                publish: '*'
