version: '3.4'
networks:
  default:
    external:
      name: '${DOCKER_NETWORK}'
services:
  database:
    image: 'mariadb:10.5'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    restart: unless-stopped
    ports:
      - '${MYSQL_EXT_PORT}:3306'
  php:
    build:
      context: ./docker/php-fpm/
      dockerfile: Dockerfile
      args:
        TIMEZONE: '${TIMEZONE}'
        docker_proxy: '${PROXY}'
        dockers_proxy: '${PROXYS}'
        no_proxy: '${NO_PROXY}'
        apply_acl_to_root: '${ROOT_ACL:-0}'
        jwt_pass: '${JWT_PASSPHRASE}'
    volumes:
      - './:/var/www/sfuxturbo/'
    ports:
      - '9000:9000'
    restart: unless-stopped
    depends_on:
      - database
  nginx:
    build: ./docker/nginx/
    image: 'nginx:1.19.0-alpine'
    volumes:
      - './:/var/www/sfuxturbo/'
    ports:
      - '${NGINX_EXT_PORT}:80'
    restart: unless-stopped
    depends_on:
      - php
  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    ports:
      - '${PMA_EXT_PORT}:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=database
    restart: unless-stopped
    depends_on:
      - database
