version: '3.4'
networks:
  default:
    external:
      name: '${DOCKER_NETWORK}'
services:
  database:
    image: 'mariadb:10.5'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    restart: unless-stopped
    ports:
      - '${MYSQL_EXT_PORT:-8086}:3306'
  php:
    build:
      context: ./docker/php-fpm/
      dockerfile: Dockerfile
      target: sfuxturbo_php
      args:
        TIMEZONE: '${TIMEZONE}'
        docker_proxy: '${PROXY}'
        dockers_proxy: '${PROXYS}'
        no_proxy: '${NO_PROXY}'
        apply_acl_to_root: '${ROOT_ACL:-0}'
        jwt_pass: '${JWT_PASSPHRASE}'
    volumes:
      - './:/var/www/sfuxturbo/'
      - './var:/var/www/sfuxturbo/var:rw'
      - 'php_socket:/var/run/php'
    ports:
      - '9000:9000'
    restart: unless-stopped
    depends_on:
      - database
  caddy:
    build:
      context: ./docker/caddy/
      target: sfuxturbo_caddy
    environment:
      SERVER_NAME: '${SERVER_NAME:-localhost, caddy:80}'
      MERCURE_PUBLISHER_JWT_KEY: '${MERCURE_PUBLISHER_JWT_KEY:-!ChangeMe!}'
      MERCURE_SUBSCRIBER_JWT_KEY: '${MERCURE_SUBSCRIBER_JWT_KEY:-!ChangeMe!}'
    restart: unless-stopped
    volumes:
      - 'php_socket:/var/run/php'
      - 'caddy_data:/data'
      - 'caddy_config:/config'
      - './docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro'
      - './public:/srv/app/public'
    ports:
      - target: 80
        published: ${MERCURE_EXT_PORT:-8080}
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
      - target: 443
        published: 443
        protocol: udp
  nginx:
    build: ./docker/nginx/
    image: 'nginx:1.19.0-alpine'
    volumes:
      - './:/var/www/sfuxturbo/'
    ports:
      - '${NGINX_EXT_PORT:-8000}:80'
    restart: unless-stopped
    depends_on:
      - php
  encore:
    build:
      context: ./docker/encore/
      args:
        docker_proxy: '${PROXY}'
        dockers_proxy: '${PROXYS}'
        no_proxy: '${NO_PROXY}'
    image: 'node:12'
    volumes:
      - './:/var/www/sfuxturbo/'
    ports:
      - '${NODE_EXT_PORT:-8004}:8080'
    restart: unless-stopped
  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    ports:
      - '${PMA_EXT_PORT:-8001}:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=database
    restart: unless-stopped
    depends_on:
      - database
volumes:
  php_socket: null
  caddy_data: null
  caddy_config: null
