version: '3.4'
networks:
  default:
    external:
      name: '${DOCKER_NETWORK}'
services:
  database:
    image: 'mariadb:10.5'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - './docker/sqld/initSqld.sql:/docker-entrypoint-initdb.d/1.sql'
    restart: unless-stopped
    ports:
      - '${MYSQL_EXT_PORT:-8006}:3306'
  php:
    build:
      context: ./docker/php-fpm/
      dockerfile: Dockerfile
      args:
        TIMEZONE: '${TIMEZONE}'
        docker_proxy: '${PROXY}'
        dockers_proxy: '${PROXYS}'
        no_proxy: '${NO_PROXY}'
        apply_acl_to_root: '${ROOT_ACL:-0}'
        jwt_pass: '${JWT_PASSPHRASE}'
    volumes:
      - './:/var/www/sfuxturbo/'
    ports:
      - '9000:9000'
    restart: unless-stopped
    depends_on:
      - database
  nginx:
    build: ./docker/nginx/
    image: 'nginx:1.19.0-alpine'
    volumes:
      - './:/var/www/sfuxturbo/'
    ports:
      - '${NGINX_EXT_PORT:-8000}:80'
    restart: unless-stopped
    depends_on:
      - php
  encore:
    build:
      context: ./docker/encore/
      args:
        docker_proxy: '${PROXY}'
        dockers_proxy: '${PROXYS}'
        no_proxy: '${NO_PROXY}'
    image: 'node:12'
    volumes:
      - './:/var/www/sfuxturbo/'
    ports:
      - '${NODE_EXT_PORT:-8080}:8080'
    restart: unless-stopped
  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    ports:
      - '${PMA_EXT_PORT:-8001}:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=database
    restart: unless-stopped
    depends_on:
      - database
  sqld:
    image: d0whc3r/wwwsqldesigner
    ports:
      - '${SQLD_EXT_PORT:-8002}:80'
    environment:
      DATABASE_SERVER: database
      DATABASE_USER: root
      DATABASE_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      DATABASE_NAME: sqld
      DATABASE_TABLE: wwwsqldesigner
      DATABASE_ROOT: root
      DATABASE_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    restart: unless-stopped
    depends_on:
      - database
